steps:
  - name: 'golang:1.15'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gcpboxtest/$BRANCH_NAME:$COMMIT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/gcptoolbox/$BRANCH_NAME:$COMMIT_SHA' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'gcpboxtest', '--image', 'gcr.io/$PROJECT_ID/gcptoolbox/$BRANCH_NAME:$COMMIT_SHA', '--region', 'asia-northeast1', '--platform', 'managed']
images:
  - 'gcr.io/$PROJECT_ID/gcptoolbox/$BRANCH_NAME:$COMMIT_SHA'